config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "csv#index"
  post '/import_csv', to: 'csv#import', as: :import_csv
  get '/search', to: 'csv#search_vehicles'
  post '/generate_customers_report', to: 'csv#generate_customers_report_by_nationality', defaults: { format: 'csv' }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates_presence_of :name
  has_many :vehicles, dependent: :destroy
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  validates_presence_of :chassis_number

  belongs_to :customer

  scope :searched_vehicles, -> (search_term) { joins(:customer).where('vehicles.model LIKE ? or customers.name LIKE ?', "%#{search_term}%", "%#{search_term}%") }


  def self.customers_by_nationality(vehicles_data)
    vehicles_data.select("customers.nationality as nationality, count(*) as number_of_customers").group('customers.nationality')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/csv_controller.rb
class CsvController < ApplicationController
  before_action :validate_file, only: [:import]
  before_action :initialize_vehicle_csv_service, only: [:index, :search_vehicles, :generate_customers_report_by_nationality]

  def index
    @vehicles_data = @vehicle_csv_service.vehicles_data
  end

  def import
  	import_csv_service = ImportCsv.new(params[:file])
  	import_csv_service.call

  	if import_csv_service.error.present?
      redirect_to root_url, alert: "CSV data not imported successfully"
  	else
      redirect_to root_url, notice: "CSV data imported successfully"
  	end
  end

  def search_vehicles
    @searched_data = @vehicle_csv_service.searched_data(params[:search])
    respond_to :js
  end

  def generate_customers_report_by_nationality
    respond_to do |format|
      format.csv { send_data @vehicle_csv_service.generate_customers_report, filename: "customer-report-#{Time.now.to_i}.csv" }
    end
  end


  private

  def validate_file
    redirect_to root_url, alert: "File not uploaded" if params[:file].blank?
  end

  def initialize_vehicle_csv_service
    @vehicle_csv_service = VehicleCsv.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/csv_helper.rb
module CsvHelper
end

app/views/csv/_table_actions.html.erb
<div class='form-inline mt-4 flex-end mb-3'>
  <%= form_tag(search_path, method: :get, remote: true) do %>
    <%= text_field_tag(:search, params[:search], placeholder: 'Press enter to search', class: 'form-control') %>
    <%= submit_tag 'Search', class: 'mx-sm-2 btn btn-primary' %>
  <% end %>

  <%= form_tag(generate_customers_report_path, method: :post) do %>
    <%= button_tag 'Generate Customer Report', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/csv/_vehicles_data_table.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Nationality</th>
      <th>Email</th>
      <th>Model</th>
      <th>Year</th>
      <th>Chassis Number</th>
      <th>Color</th>
      <th>Registration Date</th>
      <th>Odometer Reading</th>
    </tr>
  </thead>
  <tbody>
    <% vehicles_data.each do |vehicle| %>
      <tr>
        <td><%= vehicle.customer.name %></td>
        <td><%= vehicle.customer.nationality %></td>
        <td><%= vehicle.customer.email %></td>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.year %></td>
        <td><%= vehicle.chassis_number %></td>
        <td><%= vehicle.color %></td>
        <td><%= vehicle.registration_date %></td>
        <td><%= vehicle.odometer_reading %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/csv/index.html.erb
<h4>Vehicle Data</h4>

<% if @vehicles_data.present? %>
  <%= render 'table_actions' %>

  <div id='vehicles_data_table' >
    <%= render 'vehicles_data_table', vehicles_data: @vehicles_data %>
  </div>

<% else %>
  <p>No available data.<p> 
<% end %>

<div class="mt-5">
  <h4>Import CSV Data</h4>
  <%= form_tag import_csv_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/csv/search_vehicles.js.erb
<% if @searched_data.present? %>
  $("#vehicles_data_table").html("<%= j render(:partial => 'csv/vehicles_data_table', locals: {vehicles_data: @searched_data}) %>");
<% else %>
  $("#vehicles_data_table").html("<h6>No data found.</h6>");
<% end %>  

app/views/layouts/_messages.html.erb
<% if notice.present? %>
  <script type="text/javascript">
    Swal.fire({
      icon: 'success',
      title: 'Good job!',
      text: `<%= notice.html_safe %>`
    })
  </script>
<% end %>

<% if alert.present? %>
  <script type="text/javascript">
    Swal.fire({
      icon: 'error',
      title: 'Error',
      text: "<%= alert %>",
    })
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechnicalAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark justify-content-center">
    <a class="navbar-brand" href="#">Beema Vehicle Report</a>
  </nav>

  <body>
    <%= render 'layouts/messages' %>
    <div class="container main-container mt-5">
      <%= yield %>
    </div>
  </body>
</html>